FROM python:3.10

WORKDIR /app

COPY ../back-end/snappfood/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY ../back-end/snappfood .


RUN chmod +x entrypoint.sh

RUN apt-get update && apt-get install -y netcat-openbsd

EXPOSE 8000

ENTRYPOINT ["/app/entrypoint.sh"]

CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
