FROM node:latest

WORKDIR /app

COPY ../front-end/package*.json ./
RUN npm install

COPY ../front-end/ ./

RUN npm run build

RUN npm install -g serve

EXPOSE 3000

CMD ["serve", "-s", "build", "-l", "3000"]
