name: Django CI

on:
  push:
    branches: [ "back-end" ]  
  pull_request:
    branches: [ "back-end" ]  

jobs:
  build:
    runs-on: windows-latest 
    strategy:
      matrix:
        python-version: [3.12] 

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Dependencies
      run: |
        cd back-end/snappfood
        python -m pip install --upgrade pip 
        pip install -r requirements.txt

    - name: Run Tests
      run: |
        cd back-end/snappfood
        python manage.py test  # Run Django tests
